version: "3.9"
services:
  zoo_db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  zoo-app:
    image: zoo-api-service
    ports:
      - "1000:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dockercompose
    depends_on:
      -zoo_db
